name: tena_med_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  go_router: ^13.2.0
  freezed_annotation: ^2.4.1
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mockito: ^5.0.17
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/doctors.png
      - assets/images/doctor_avatar.png
      - assets/images/doc1.jpg
      - assets/images/doc2.jpg
